session_name: chatsune
windows:
  - window_name: chatsune
    layout: main-vertical
    options:
      main-pane-width: 20%
    panes:
      - shell_command:
          - cd ~/Documents/Projects/chatsune
          # - nvim Notes.md ToDo.md
          - open-project
      - shell_command:
          - tmux resizep -y 85%
          - filelist-open "startup_files.txt" chatsune
        focus: true
      - clear
